// B站开放接口 - 视频稿件投递 bilibili-webapp

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.0
// source: bilibili-webapp/upload.proto

package bilibili_webapp

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitPartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId    string            `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AccessToken string            `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Body        *InitPartReq_Body `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *InitPartReq) Reset() {
	*x = InitPartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitPartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPartReq) ProtoMessage() {}

func (x *InitPartReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPartReq.ProtoReflect.Descriptor instead.
func (*InitPartReq) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{0}
}

func (x *InitPartReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *InitPartReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *InitPartReq) GetBody() *InitPartReq_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type InitPartRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ttl     int32             `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Data    *InitPartRes_Data `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *InitPartRes) Reset() {
	*x = InitPartRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitPartRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPartRes) ProtoMessage() {}

func (x *InitPartRes) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPartRes.ProtoReflect.Descriptor instead.
func (*InitPartRes) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{1}
}

func (x *InitPartRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InitPartRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitPartRes) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *InitPartRes) GetData() *InitPartRes_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadPartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadToken string `protobuf:"bytes,1,opt,name=upload_token,json=uploadToken,proto3" json:"upload_token,omitempty"`
	PartNumber  int64  `protobuf:"varint,2,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
}

func (x *UploadPartReq) Reset() {
	*x = UploadPartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartReq) ProtoMessage() {}

func (x *UploadPartReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartReq.ProtoReflect.Descriptor instead.
func (*UploadPartReq) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{2}
}

func (x *UploadPartReq) GetUploadToken() string {
	if x != nil {
		return x.UploadToken
	}
	return ""
}

func (x *UploadPartReq) GetPartNumber() int64 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

type UploadPartRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ttl     int32  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *UploadPartRes) Reset() {
	*x = UploadPartRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPartRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartRes) ProtoMessage() {}

func (x *UploadPartRes) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartRes.ProtoReflect.Descriptor instead.
func (*UploadPartRes) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{3}
}

func (x *UploadPartRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UploadPartRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadPartRes) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type CompletePartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadToken string `protobuf:"bytes,1,opt,name=upload_token,json=uploadToken,proto3" json:"upload_token,omitempty"`
}

func (x *CompletePartReq) Reset() {
	*x = CompletePartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletePartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletePartReq) ProtoMessage() {}

func (x *CompletePartReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletePartReq.ProtoReflect.Descriptor instead.
func (*CompletePartReq) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{4}
}

func (x *CompletePartReq) GetUploadToken() string {
	if x != nil {
		return x.UploadToken
	}
	return ""
}

type CompletePartRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ttl     int32  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *CompletePartRes) Reset() {
	*x = CompletePartRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletePartRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletePartRes) ProtoMessage() {}

func (x *CompletePartRes) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletePartRes.ProtoReflect.Descriptor instead.
func (*CompletePartRes) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{5}
}

func (x *CompletePartRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CompletePartRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CompletePartRes) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type UploadCoverReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId    string               `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AccessToken string               `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Body        *UploadCoverReq_Body `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *UploadCoverReq) Reset() {
	*x = UploadCoverReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadCoverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCoverReq) ProtoMessage() {}

func (x *UploadCoverReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCoverReq.ProtoReflect.Descriptor instead.
func (*UploadCoverReq) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{6}
}

func (x *UploadCoverReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UploadCoverReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UploadCoverReq) GetBody() *UploadCoverReq_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type UploadCoverRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ttl     int32                `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Data    *UploadCoverRes_Data `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UploadCoverRes) Reset() {
	*x = UploadCoverRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadCoverRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCoverRes) ProtoMessage() {}

func (x *UploadCoverRes) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCoverRes.ProtoReflect.Descriptor instead.
func (*UploadCoverRes) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{7}
}

func (x *UploadCoverRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UploadCoverRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadCoverRes) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *UploadCoverRes) GetData() *UploadCoverRes_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadToken string `protobuf:"bytes,1,opt,name=upload_token,json=uploadToken,proto3" json:"upload_token,omitempty"`
	Body        []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *UploadReq) Reset() {
	*x = UploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReq) ProtoMessage() {}

func (x *UploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReq.ProtoReflect.Descriptor instead.
func (*UploadReq) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{8}
}

func (x *UploadReq) GetUploadToken() string {
	if x != nil {
		return x.UploadToken
	}
	return ""
}

func (x *UploadReq) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type UploadRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ttl     int32  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *UploadRes) Reset() {
	*x = UploadRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRes) ProtoMessage() {}

func (x *UploadRes) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRes.ProtoReflect.Descriptor instead.
func (*UploadRes) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{9}
}

func (x *UploadRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UploadRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadRes) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type UploadImageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId    string               `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AccessToken string               `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Body        *UploadImageReq_Body `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *UploadImageReq) Reset() {
	*x = UploadImageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageReq) ProtoMessage() {}

func (x *UploadImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageReq.ProtoReflect.Descriptor instead.
func (*UploadImageReq) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{10}
}

func (x *UploadImageReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UploadImageReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UploadImageReq) GetBody() *UploadImageReq_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type UploadImageRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ttl     int32                `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Data    *UploadImageRes_Data `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UploadImageRes) Reset() {
	*x = UploadImageRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRes) ProtoMessage() {}

func (x *UploadImageRes) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRes.ProtoReflect.Descriptor instead.
func (*UploadImageRes) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{11}
}

func (x *UploadImageRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UploadImageRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadImageRes) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *UploadImageRes) GetData() *UploadImageRes_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type InitPartReq_Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Utype string `protobuf:"bytes,2,opt,name=utype,proto3" json:"utype,omitempty"`
}

func (x *InitPartReq_Body) Reset() {
	*x = InitPartReq_Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitPartReq_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPartReq_Body) ProtoMessage() {}

func (x *InitPartReq_Body) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPartReq_Body.ProtoReflect.Descriptor instead.
func (*InitPartReq_Body) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{0, 0}
}

func (x *InitPartReq_Body) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitPartReq_Body) GetUtype() string {
	if x != nil {
		return x.Utype
	}
	return ""
}

type InitPartRes_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadToken string `protobuf:"bytes,1,opt,name=upload_token,json=uploadToken,proto3" json:"upload_token,omitempty"`
}

func (x *InitPartRes_Data) Reset() {
	*x = InitPartRes_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitPartRes_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPartRes_Data) ProtoMessage() {}

func (x *InitPartRes_Data) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPartRes_Data.ProtoReflect.Descriptor instead.
func (*InitPartRes_Data) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{1, 0}
}

func (x *InitPartRes_Data) GetUploadToken() string {
	if x != nil {
		return x.UploadToken
	}
	return ""
}

type UploadCoverReq_Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File []byte `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *UploadCoverReq_Body) Reset() {
	*x = UploadCoverReq_Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadCoverReq_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCoverReq_Body) ProtoMessage() {}

func (x *UploadCoverReq_Body) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCoverReq_Body.ProtoReflect.Descriptor instead.
func (*UploadCoverReq_Body) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{6, 0}
}

func (x *UploadCoverReq_Body) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type UploadCoverRes_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *UploadCoverRes_Data) Reset() {
	*x = UploadCoverRes_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadCoverRes_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCoverRes_Data) ProtoMessage() {}

func (x *UploadCoverRes_Data) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCoverRes_Data.ProtoReflect.Descriptor instead.
func (*UploadCoverRes_Data) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{7, 0}
}

func (x *UploadCoverRes_Data) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UploadImageReq_Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File      []byte `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Watermark bool   `protobuf:"varint,2,opt,name=watermark,proto3" json:"watermark,omitempty"`
}

func (x *UploadImageReq_Body) Reset() {
	*x = UploadImageReq_Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImageReq_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageReq_Body) ProtoMessage() {}

func (x *UploadImageReq_Body) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageReq_Body.ProtoReflect.Descriptor instead.
func (*UploadImageReq_Body) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{10, 0}
}

func (x *UploadImageReq_Body) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *UploadImageReq_Body) GetWatermark() bool {
	if x != nil {
		return x.Watermark
	}
	return false
}

type UploadImageRes_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url  string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Size int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *UploadImageRes_Data) Reset() {
	*x = UploadImageRes_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_webapp_upload_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImageRes_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRes_Data) ProtoMessage() {}

func (x *UploadImageRes_Data) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_webapp_upload_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRes_Data.ProtoReflect.Descriptor instead.
func (*UploadImageRes_Data) Descriptor() ([]byte, []int) {
	return file_bilibili_webapp_upload_proto_rawDescGZIP(), []int{11, 0}
}

func (x *UploadImageRes_Data) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadImageRes_Data) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_bilibili_webapp_upload_proto protoreflect.FileDescriptor

var file_bilibili_webapp_upload_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2d, 0x77, 0x65, 0x62, 0x61, 0x70,
	0x70, 0x2f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xba, 0x01, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x39, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a, 0x30, 0x0a, 0x04,
	0x42, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x74, 0x79, 0x70, 0x65, 0x22, 0xb3,
	0x01, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x74, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x39,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x29, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x53, 0x0a, 0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x72, 0x74,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70,
	0x61, 0x72, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x4f, 0x0a, 0x0d, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x22, 0x34, 0x0a, 0x0f, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a,
	0x0c, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x51, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x74, 0x74, 0x6c, 0x22, 0xaa, 0x01, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x3c, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x62, 0x69,
	0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x1a, 0x1a, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x22, 0xa8, 0x01, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x74, 0x74, 0x6c, 0x12, 0x3c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62,
	0x69, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x18, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x42, 0x0a, 0x09, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22,
	0x4b, 0x0a, 0x09, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x22, 0xc8, 0x01, 0x0a,
	0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x3c, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a, 0x38, 0x0a,
	0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x61, 0x74,
	0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x77, 0x61,
	0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0xbc, 0x01, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x3c, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x2c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x32, 0x9a, 0x06, 0x0a, 0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7c, 0x0a, 0x08, 0x49, 0x6e, 0x69, 0x74,
	0x50, 0x61, 0x72, 0x74, 0x12, 0x20, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x62, 0x69,
	0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x50,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x49, 0x6e, 0x69,
	0x74, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x22, 0x2c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x26,
	0x22, 0x1e, 0x2f, 0x61, 0x72, 0x63, 0x6f, 0x70, 0x65, 0x6e, 0x2f, 0x66, 0x6e, 0x2f, 0x61, 0x72,
	0x63, 0x68, 0x69, 0x76, 0x65, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2f, 0x69, 0x6e, 0x69, 0x74,
	0x3a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x73, 0x0a, 0x0a, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x50, 0x61, 0x72, 0x74, 0x12, 0x22, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x62, 0x69,
	0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x22, 0x1d, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x17, 0x22, 0x15, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2f, 0x76, 0x32, 0x2f,
	0x70, 0x61, 0x72, 0x74, 0x2f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x86, 0x01, 0x0a, 0x0c,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x12, 0x24, 0x2e, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x24, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x62, 0x69, 0x6c, 0x69,
	0x62, 0x69, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x22, 0x2a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x24,
	0x22, 0x22, 0x2f, 0x61, 0x72, 0x63, 0x6f, 0x70, 0x65, 0x6e, 0x2f, 0x66, 0x6e, 0x2f, 0x61, 0x72,
	0x63, 0x68, 0x69, 0x76, 0x65, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x8d, 0x01, 0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43,
	0x6f, 0x76, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x62, 0x69,
	0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x34,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2e, 0x22, 0x20, 0x2f, 0x61, 0x72, 0x63, 0x6f, 0x70, 0x65, 0x6e,
	0x2f, 0x66, 0x6e, 0x2f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2f, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x2f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x3a, 0x0a, 0x62, 0x6f, 0x64, 0x79, 0x2c, 0x6d,
	0x75, 0x6c, 0x74, 0x69, 0x12, 0x6d, 0x0a, 0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1e,
	0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1e,
	0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x22, 0x23,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x22, 0x10, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2f, 0x76,
	0x32, 0x2f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x3a, 0x09, 0x62, 0x6f, 0x64, 0x79, 0x2c, 0x62,
	0x79, 0x74, 0x65, 0x12, 0x8d, 0x01, 0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x12, 0x23, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x62, 0x69, 0x6c,
	0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x22, 0x34, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x2e, 0x22, 0x20, 0x2f, 0x61, 0x72, 0x63, 0x6f, 0x70, 0x65, 0x6e, 0x2f,
	0x66, 0x6e, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2f, 0x75, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x3a, 0x0a, 0x62, 0x6f, 0x64, 0x79, 0x2c, 0x6d, 0x75,
	0x6c, 0x74, 0x69, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x65, 0x76, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69,
	0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2d, 0x77, 0x65, 0x62, 0x61, 0x70, 0x70, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bilibili_webapp_upload_proto_rawDescOnce sync.Once
	file_bilibili_webapp_upload_proto_rawDescData = file_bilibili_webapp_upload_proto_rawDesc
)

func file_bilibili_webapp_upload_proto_rawDescGZIP() []byte {
	file_bilibili_webapp_upload_proto_rawDescOnce.Do(func() {
		file_bilibili_webapp_upload_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_webapp_upload_proto_rawDescData)
	})
	return file_bilibili_webapp_upload_proto_rawDescData
}

var file_bilibili_webapp_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_bilibili_webapp_upload_proto_goTypes = []interface{}{
	(*InitPartReq)(nil),         // 0: member.bilibili.com.InitPartReq
	(*InitPartRes)(nil),         // 1: member.bilibili.com.InitPartRes
	(*UploadPartReq)(nil),       // 2: member.bilibili.com.UploadPartReq
	(*UploadPartRes)(nil),       // 3: member.bilibili.com.UploadPartRes
	(*CompletePartReq)(nil),     // 4: member.bilibili.com.CompletePartReq
	(*CompletePartRes)(nil),     // 5: member.bilibili.com.CompletePartRes
	(*UploadCoverReq)(nil),      // 6: member.bilibili.com.UploadCoverReq
	(*UploadCoverRes)(nil),      // 7: member.bilibili.com.UploadCoverRes
	(*UploadReq)(nil),           // 8: member.bilibili.com.UploadReq
	(*UploadRes)(nil),           // 9: member.bilibili.com.UploadRes
	(*UploadImageReq)(nil),      // 10: member.bilibili.com.UploadImageReq
	(*UploadImageRes)(nil),      // 11: member.bilibili.com.UploadImageRes
	(*InitPartReq_Body)(nil),    // 12: member.bilibili.com.InitPartReq.Body
	(*InitPartRes_Data)(nil),    // 13: member.bilibili.com.InitPartRes.Data
	(*UploadCoverReq_Body)(nil), // 14: member.bilibili.com.UploadCoverReq.Body
	(*UploadCoverRes_Data)(nil), // 15: member.bilibili.com.UploadCoverRes.Data
	(*UploadImageReq_Body)(nil), // 16: member.bilibili.com.UploadImageReq.Body
	(*UploadImageRes_Data)(nil), // 17: member.bilibili.com.UploadImageRes.Data
}
var file_bilibili_webapp_upload_proto_depIdxs = []int32{
	12, // 0: member.bilibili.com.InitPartReq.body:type_name -> member.bilibili.com.InitPartReq.Body
	13, // 1: member.bilibili.com.InitPartRes.data:type_name -> member.bilibili.com.InitPartRes.Data
	14, // 2: member.bilibili.com.UploadCoverReq.body:type_name -> member.bilibili.com.UploadCoverReq.Body
	15, // 3: member.bilibili.com.UploadCoverRes.data:type_name -> member.bilibili.com.UploadCoverRes.Data
	16, // 4: member.bilibili.com.UploadImageReq.body:type_name -> member.bilibili.com.UploadImageReq.Body
	17, // 5: member.bilibili.com.UploadImageRes.data:type_name -> member.bilibili.com.UploadImageRes.Data
	0,  // 6: member.bilibili.com.UploadService.InitPart:input_type -> member.bilibili.com.InitPartReq
	2,  // 7: member.bilibili.com.UploadService.UploadPart:input_type -> member.bilibili.com.UploadPartReq
	4,  // 8: member.bilibili.com.UploadService.CompletePart:input_type -> member.bilibili.com.CompletePartReq
	6,  // 9: member.bilibili.com.UploadService.UploadCover:input_type -> member.bilibili.com.UploadCoverReq
	8,  // 10: member.bilibili.com.UploadService.Upload:input_type -> member.bilibili.com.UploadReq
	10, // 11: member.bilibili.com.UploadService.UploadImage:input_type -> member.bilibili.com.UploadImageReq
	1,  // 12: member.bilibili.com.UploadService.InitPart:output_type -> member.bilibili.com.InitPartRes
	3,  // 13: member.bilibili.com.UploadService.UploadPart:output_type -> member.bilibili.com.UploadPartRes
	5,  // 14: member.bilibili.com.UploadService.CompletePart:output_type -> member.bilibili.com.CompletePartRes
	7,  // 15: member.bilibili.com.UploadService.UploadCover:output_type -> member.bilibili.com.UploadCoverRes
	9,  // 16: member.bilibili.com.UploadService.Upload:output_type -> member.bilibili.com.UploadRes
	11, // 17: member.bilibili.com.UploadService.UploadImage:output_type -> member.bilibili.com.UploadImageRes
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_bilibili_webapp_upload_proto_init() }
func file_bilibili_webapp_upload_proto_init() {
	if File_bilibili_webapp_upload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_webapp_upload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitPartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitPartRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadPartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadPartRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletePartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletePartRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadCoverReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadCoverRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadImageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadImageRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitPartReq_Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitPartRes_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadCoverReq_Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadCoverRes_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadImageReq_Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_webapp_upload_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadImageRes_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_webapp_upload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bilibili_webapp_upload_proto_goTypes,
		DependencyIndexes: file_bilibili_webapp_upload_proto_depIdxs,
		MessageInfos:      file_bilibili_webapp_upload_proto_msgTypes,
	}.Build()
	File_bilibili_webapp_upload_proto = out.File
	file_bilibili_webapp_upload_proto_rawDesc = nil
	file_bilibili_webapp_upload_proto_goTypes = nil
	file_bilibili_webapp_upload_proto_depIdxs = nil
}
